Development
LeticiaSan/Welcome-Feature pull request #5
Opened 2021-09-08 16:55 UTC by LeticiaSan

Finalizei a US02.
Melhore o método desenvolvido pela US1 de modo que o mesmo parâmetro string seja capaz de manipular, além do CPF, um endereço de e-mail, retornando a mesma mensagem de boas-vindas caso o usuário seja identificado pelo input.
Aguardo as revisões para continuar.

2021-09-10 14:22 UTC, oswaldobapvicjr commented on src/Welcome.java
> +	    if (email != null && email.length() > 0) {
It's usually a better idea to check `string.isEmpty()` rather than `string.length() > 0`. Can you research on it and explain "why"?

2021-09-10 14:22 UTC, oswaldobapvicjr commented on src/Welcome.java
> +	    if (cpf != null && cpf.length() > 0) {
Same here (lenght vs isEmpty)

2021-09-10 14:22 UTC, oswaldobapvicjr commented on src/Welcome.java
> +	public static boolean verifyCpfRegex(String cpf) {
This method looks like a duplication of the previous one `verifyEmailRegex`.
Please take the equal part of both and extract a common method, so you have less duplication and more reuse.

2021-09-10 14:22 UTC, oswaldobapvicjr commented on src/Welcome.java
> +		return cpfOnlyNum.replace(".","").replace("-","").replace(" ", "");
What is the expected behavior if the String parameter is null?

2021-09-10 14:22 UTC, oswaldobapvicjr commented on src/Welcome.java
> +	public String searchUserByCpf(Map<String, User> map, String inputCpf){
So, the user has to always pass the map as a parameter. Please refactor in a way that the user doesn't need to pass the map, only the CPF, for better simplicity.

2021-09-10 14:22 UTC, oswaldobapvicjr commented on src/Welcome.java
> +		for(int i = 0; i < 1; i--){
That seems overcomplicated. Seems like the look will never reach an end. Was this on purpose? If yes, why not simplify it with a `while(true)` ?

2021-09-10 14:22 UTC, oswaldobapvicjr commented on src/Welcome.java
> +		map.put(user2.email, user2);
Wouldn't the same map get so huge that it could impact searching performance one day?

2021-09-10 14:22 UTC, oswaldobapvicjr commented on src/Welcome.java
> +			if(Welcome.verifyCpfRegex(searchVariable) == true) {
This can be simplified (you don't need to check if boolean == true), simple consider using the boolean value. (the same goes for line 73)

2021-09-10 14:34 UTC, oswaldobapvicjr requested changes
Please check my comments and reach me if you have any questions.

2021-09-10 16:45 UTC, LeticiaSan commented on src/Welcome.java
> +		for(int i = 0; i < 1; i--){
I've tryed this before, the problem is that if I use the while(true), everything that happens afterwards results in an error, because it never comes your turn. Doesn't result in an error when I use for.

2021-09-17 15:19 UTC, LeticiaSan commented
Ajustes dos comentários anteriores.

2021-09-17 15:20 UTC, closed without merging