Change Request 1
LeticiaSan/Welcome-Feature pull request #8
Opened 2021-09-21 19:04 UTC by LeticiaSan

2021-09-21 20:06 UTC, oswaldobapvicjr requested changes

2021-09-21 20:06 UTC, oswaldobapvicjr commented on src/WelcomeServices.java
> +			return s.equals("true") || s.equals("1");
Probable NullPointerException raiser here. Either handle or document it.

2021-09-21 20:06 UTC, oswaldobapvicjr commented on src/Welcome.java
> +		String enableSearchByEmail = "";
This should be loaded from the welcome.properties file, according to the CR requirement.

2021-09-21 20:06 UTC, oswaldobapvicjr commented on src/WelcomeServices.java
> +			if(user != null && enableSearchByEmail) {
Please re-evaluate this metho. You are searching the user even if the search by email is disabled. Can you explain why this is not a good idea?

2021-09-22 20:04 UTC, LeticiaSan commented on src/WelcomeServices.java
> +			if(user != null && enableSearchByEmail) {
it's an unnecessary search, slowing down the program. I already fixed it,

2021-09-22 20:09 UTC, closed without merging